### ISSUE TITLE
How to prevent the white 'flash' on image load

### ISSUE THREAD

**Issue by ZuzooVn** [anpho/WebImageView#2]
Hi @anphorea 

Thanks for your great work.

I call setUrl per 1 second in order to reloading my WebImageView.
I have the white "flash" animation with this method.
I deleted resetImage(); in the serUrl, but nothing's changed.

Do you have any suggestion ?

Thank you

Nam Vu

**Comment by MerrickZ** [comment]
change image 1 / sec ? why ?
in some situation when network speed is slow, that may cause problems.

plus I don't know how to deal with the white flash you said, didn't try to reload images per second before.
is it caused by the image load effect ? when I set it to fade-zoom it flashes ..
![image](https://cloud.githubusercontent.com/assets/1021332/9021823/36a5c91e-388b-11e5-9ba9-57b564b754d1.png)

**Comment by ZuzooVn** [comment]
I changed from this code

`setImage(Image(imageData));`

to this code

```QImage image;
image.loadFromData(imageData);
QImage swappedImage = image.rgbSwapped();
if(swappedImage.format() != QImage::Format_RGB32) {
    swappedImage = swappedImage.convertToFormat(QImage::Format_RGB32);
}
const bb::ImageData imageDataVar = bb::ImageData::fromPixels(swappedImage.bits(), bb::PixelFormat::RGBX, swappedImage.width(), swappedImage.height(), swappedImage.bytesPerLine());

setImage(Image(imageDataVar));```

Everything is OK.

**Comment by MerrickZ** [comment]
That's awesome!
let me do some test.
thanks

**Comment by ZuzooVn** [comment]
@anphorea 
How is it going?
Can I make a pull request?

**Comment by MerrickZ** [comment]
yes please :)
